# Generated by Django 4.2.7 on 2023-12-15 22:13

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('locate', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id_delivery', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryStat',
            fields=[
                ('id_delivery_stat', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_stat', models.IntegerField(blank=True, null=True)),
                ('state_desc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'delivery_stat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id_good', models.AutoField(primary_key=True, serialize=False)),
                ('good_price', models.IntegerField(blank=True, null=True)),
                ('short_info', models.CharField(blank=True, max_length=255, null=True)),
                ('good_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HasOrderStruct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'has_order_struct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order1',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.IntegerField()),
                ('order_price', models.IntegerField(blank=True, null=True)),
                ('order_info', models.CharField(blank=True, max_length=255, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStruct',
            fields=[
                ('id_order_struct', models.AutoField(primary_key=True, serialize=False)),
                ('count_of_prod', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_struct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id_storage', models.AutoField(primary_key=True, serialize=False)),
                ('locate', models.CharField(blank=True, max_length=255, null=True)),
                ('worktime', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'storage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_client', models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='marketplace.client')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
