# Generated by Django 4.2.7 on 2023-12-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hasorderstruct',
            options={},
        ),
    ]
